### PR TITLE
Nested RouteTableGroup

### PR DESCRIPTION
**Pull request by Rumbeer**
I think that when creating a new `RouteTableGroup` its `DotvvmRouteTable` should be added to all of its parent `DotvvmRouteTables` and not just the first one.

### CODE REVIEW

**Comment by exyi** [comment]
I don't think so, the groups should form the hierarchy.

**Comment by Rumbeer** [comment]
They still form a hierarchy, but you can retrieve all child groups from the parent (like routes) and there cannot be conflicting group names between different levels.

**Comment by exyi** [comment]
Kind of, they would form a stupid hierarchy, where you'd not know if it's your child or grandchild or what... All hierarchies you can find in software have only parent-child relations recorded, you can walk the tree if you want. Have a look at syntax trees, dotvvm control trees, filesystem trees, ... there is no flattening anywhere.

**Comment by Rumbeer** [comment]
Ok, that sounds right.

**Pull request closed without merging**
