### PR TITLE
Added Changed property to GridViewTextColumn

### PR DESCRIPTION
**Pull request by Rumbeer**
Issue https://github.com/riganti/dotvvm/issues/368

I chose the name `Changed` for the property to be consistent with other properties with similar functionality.

### CODE REVIEW

**Comment by djanosik** [comment]
I think the name should be `ChangedBinding` and its type should be `ICommandBinding`. But I am not sure about that.  @exyi

**Comment by exyi** [comment]
@djanosik I agree with that because it's more consistent but I think that it does not matter much in this case. In this case, there is actually no reason why would the value be disallowed except [this error](https://github.com/riganti/dotvvm/pull/443/files#diff-ab0255b92599e438c1cfeb716182f1b6R96) (although I haven't seen value usage of `Command` property...)

**Comment by djanosik** [comment]
It's more about convention. What properties on "wrapping" controls like GridViewColumn should have the `Binding` suffix? All props that are copied to wrapped control?

**Comment by Rumbeer** [comment]
Ok, so I will change the property to `ChangedBinding`.

**Pull request merged**
