### PR TITLE
Binding compiler: Added support for semicolon

### PR DESCRIPTION
**Pull request by exyi**
* It basically works like a binary expression which returns the right expression after execution of the left one
* expressions without right node like `expr;` return void

### CODE REVIEW

**Comment by djanosik** [comment]
@exyi @tomasherceg I suppose this change is related to REST API bindings, right? Should we merge it? What is the status of RES API bindings?

**Comment by exyi** [comment]
On Thu, 2017-12-07 at 17:30 +0000, Dusan Janosik wrote:
> @exyi @tomasherceg I suppose this change is related to REST API
> bindings, right?
Yes it is, it is the main reason we need this, but it may be used in
other bindings too.

> Should we merge it?
It is not accepted... It it related to compiler - @Mylan719 would you
like to have a look at it?

> What is the status of RES API bindings?

The stuff that is implemented is implemented... It's untested, and I
don't khow how the tests should look like.

**Comment by tomasherceg** [comment]
@Mylan719 Did you have time to look at it? 
I would like to merge this so we can finalize the REST API bindings. Without the semicolon operator, the feature is not very useful.

**Comment by exyi** [comment]
I'm merging it, CI seems to be happy and you had enough time for protests...

**Pull request merged**
