### PR TITLE
Updated Newtonsoft.Json

### PR DESCRIPTION
**Pull request by acizmarik**

### CODE REVIEW

**Comment by exyi** [comment]
Do we really need to update the minimal required version of DotVVM.Framework and DotVVM.Core?

**Comment by acizmarik** [comment]
We could keep the version. But then we should set the maximum recursion depth for JSON parsing. Not sure which approach is better for us

**Comment by exyi** [comment]
I'd set the recursion limit, updating 3 version may break some people so they will avoid updating to 4.1... Setting the limit could also be released as 4.0.x

**Comment by acizmarik** [comment]
Closing in favor of #1434

**Pull request closed without merging**
