### PR TITLE
bundling and minification added

### PR DESCRIPTION
**Pull request by juratime**
bundling and minification using web.optimization

### CODE REVIEW

**Comment by djanosik** [comment]
Interesting solution, but I don't think this PR should be merged. It's really bad idea to bundle and minify resources at runtime. Instead, we need to find a way to build bundles at compile time (MSBuild task? see [Bundler & Minifier](http://www.nuget.org/packages/BuildBundlerMinifier/)). It may require some changes to DotVVM resource management.

Also... WebGrease is a deprecated solution and I doubt it will ever be ported to .NET Core.

**Comment by martinsura** [comment]
Bundling resources in runtime is nice feature in development mode. (Less, Typescript compile on the fly)

But for production is better @djanosik solution.

**Comment by exyi** [comment]
@djanosik Dotvvm already contains infrastructure for bundled scripts, or similar processing of resources. However it is documented only at [ResourceManagement/BundlingResourceProcessor.cs](https://github.com/riganti/dotvvm/blob/12e5e60dab0c9a2d495f5e4d21ec0ad1a288378e/src/DotVVM.Framework/ResourceManagement/BundlingResourceProcessor.cs). I thought I had a sample for that, but I can't find it, it was probably lost when we were creating the new samples with UI tests :(. You just register which resources are in which bundle and when you reference at least one resource from the bundle, the entire bundle is loaded.

I also like compile-time processing of resources, in best case recompiled on save so I don't have to recompile the project to refresh one script, just save and reload page. WebEssentials could do that in past, now you have to use grunt or something I'm not familiar with :(

@juratime Could you please publish as separate assembly, in separate repository and as separate NuGet package, since I don't want to make DotVVM dependent on WebGrease and Antlr. Just PR some interfaces if you'd need them. Or ask for them, maybe they are already present ;).

**Comment by djanosik** [comment]
@exyi Yeah, I know about that :) You can use the mentioned Bundler & Minifier. It's a [VS extension](https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40) + [MSBuild task](http://www.nuget.org/packages/BuildBundlerMinifier/). We can do it in similar way.

**Comment by tomasherceg** [comment]
We can bundle and minify resources at runtime provided we'll cache them accordingly, and I think that there are plenty of users who don't want to install any other extensions, use grunt/gulp or other tools, they just want the framework to handle it somehow. 
Ideally the runtime bundling will be a separate DotVVM package - something like DotVVM.Utils.RuntimeBundler.

On the other hand, there must be an option to give DotVVM the bundled and minified resources manually, e.g. using MSBuild or other tooling.

We won't merge this PR as is, but I'll go though it with @juratime and we'll modify it accordingly.

**Comment by martinsura** [comment]
> and I think that there are plenty of users who don't want to install any other extensions, use grunt/gulp or other tools, they just want the framework to handle it somehow. 

+1 Exactly my usecase

**Pull request closed without merging**
