### PR TITLE
Added sample for _js.Invoke in value binding.

### PR DESCRIPTION
**Pull request by Mylan719**
I realized that `_js.Invoke` does not work in value bindings in markup control. It works nicely in the page. I added sample for problematic case.

### CODE REVIEW

**Review by Mylan719 — COMMENTED** [review]
This approach seems nicer and more general.

**Review by cafour — APPROVED** [review]
I am no expert on the translation of bindings to JS but this looks alright to me.

**Comment by acizmarik** [comment]
Can we add an UI test for this please? After that I think we can merge

**Comment by Mylan719** [comment]
I added new more complicated sample and UI tests for both samples.

**Comment by exyi** [comment]
Awesome, thank you

**Pull request merged**
